src = /var/TMP-SAFE/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/avl

MODULE := zavl

obj-$(CONFIG_ZFS) := $(MODULE).o

ccflags-y := $(ZFS_MODULE_CFLAGS) $(ZFS_MODULE_CPPFLAGS)

$(MODULE)-objs += avl.o
