src = /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/spl

MODULE := spl

obj-$(CONFIG_ZFS) := $(MODULE).o

ccflags-y := $(ZFS_MODULE_CFLAGS) $(ZFS_MODULE_CPPFLAGS)


-include /var/tmp/portage/sys-fs/zfs-kmod-9999/work/zfs-kmod-9999/module/os/linux/spl/Makefile
